nginx:
  image: nginx
  ports:
   - 80:80
  volumes:
   - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./config/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
   - ./../../src:/var/www
  links:
   - php
mysql:
  image: mysql
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root_password
   - MYSQL_DATABASE=database
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password
php:
  image: nmcteam/php56
  volumes:
    - ./config/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./../../src:/var/www
  links:
    - mysql
